name: PR - Build and Deploy
on:
  pull_request:
    paths-ignore:
      - '**/README.md'
jobs:
  run_pr-template:
    name: PR - Build
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/pr-template.yml@1389-standard-steps-for-workflows
    secrets: inherit
    with:
      componentName: secure-api-gateway-ob-uk-common