name: PR - Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**/README.md'
jobs:
  run_pr-template:
    name: PR - Build
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-pr.yml@main
    secrets: inherit
    with:
      componentName: secure-api-gateway-ob-uk-common
      dockerTag: pr-${{ github.event.number }}