name: pull-request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        name: set java and maven cache
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x64
          cache: 'maven'

      - name: Build and Test
        run: mvn -B clean package --file pom.xml

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
